/*Presentado por:
	-Maria Camila Mejia
	-Sebastian Vallejo Perez*/

CREATE DATABASE SigiBD
GO

USE SigiBD
GO

CREATE TABLE Address (
Id VARCHAR(25) PRIMARY KEY NOT NULL,
Address1 VARCHAR(30) NOT NULL,
Address2 VARCHAR(30),
PostalCode INT,
City VARCHAR(30) NOT NULL,
Country VARCHAR(30) NOT NULL
)
GO

CREATE TABLE Company (
Id VARCHAR(25) PRIMARY KEY NOT NULL,
CompanyName VARCHAR(30) NOT NULL,
Nit BIGINT NOT NULL,
Email VARCHAR(50),
PhoneNumber BIGINT,
Website VARCHAR(30),
IndustryType VARCHAR(20),
LegalRep VARCHAR(30),
Logo VARCHAR(200),
AddressId VARCHAR(25) NOT NULL,
FOREIGN KEY(AddressId) REFERENCES Address(Id)
)
GO

CREATE TABLE UserInfo (
Id VARCHAR(25) PRIMARY KEY NOT NULL,
UserName VARCHAR(30) NOT NULL,
Password VARCHAR(50) NOT NULL,
Rol VARCHAR(20) NOT NULL,
CHECK(Rol in ('ADMIN','USER')),
FirstName VARCHAR(30) NOT NULL,
MiddleName VARCHAR(30),
LastName VARCHAR(30) NOT NULL,
SecondLastName VARCHAR(30),
Email VARCHAR(50),
PhoneNumber BIGINT,
AddressId VARCHAR(25) NOT NULL,
CompanyId VARCHAR(25) NOT NULL,
FOREIGN KEY(AddressId) REFERENCES Address(Id),
FOREIGN KEY(CompanyId) REFERENCES Company(Id)
)
GO

CREATE TABLE Category (
Id VARCHAR(25) PRIMARY KEY NOT NULL,
CategoryName VARCHAR(30) NOT NULL,
CategoryColor VARCHAR(30) NOT NULL,
CompanyId VARCHAR(25) NOT NULL,
FOREIGN KEY(CompanyId) REFERENCES Company(Id)
)
GO

CREATE TABLE Supplier (
Id VARCHAR(25) PRIMARY KEY NOT NULL,
SupplierName VARCHAR(30) NOT NULL,
PhoneNumber BIGINT,
Email VARCHAR(50),
AddressId VARCHAR(25) NOT NULL,
CompanyId VARCHAR(25) NOT NULL,
FOREIGN KEY(AddressId) REFERENCES Address(Id),
FOREIGN KEY(CompanyId) REFERENCES Company(Id)
)
GO

CREATE TABLE InventoryLocation (
Id VARCHAR(25) PRIMARY KEY NOT NULL,
LocationCode VARCHAR(20) NOT NULL,
LocationName VARCHAR(30) NOT NULL,
Capacity INT NOT NULL,
CurrentStock INT NOT NULL,
IsActive BIT NOT NULL,
CompanyId VARCHAR(25) NOT NULL,
FOREIGN KEY(CompanyId) REFERENCES Company(Id)
)
GO

CREATE TABLE Product(
Id VARCHAR(25) PRIMARY KEY NOT NULL,
ProductName VARCHAR(30) NOT NULL,
UnitPrice FLOAT NOT NULL,
Stock INT NOT NULL,
CompanyId VARCHAR(25) NOT NULL,
SupplierId VARCHAR(25),
CategoryId VARCHAR(25),
InventoryLocationId VARCHAR(25),
FOREIGN KEY(CompanyId) REFERENCES Company(Id),
FOREIGN KEY(SupplierId) REFERENCES Supplier(Id) ON DELETE SET NULL,
FOREIGN KEY(CategoryId) REFERENCES Category(Id) ON DELETE SET NULL,
FOREIGN KEY(InventoryLocationId) REFERENCES InventoryLocation(Id) ON DELETE SET NULL,
)
GO

CREATE TABLE StockTransaction(
Id VARCHAR(25) PRIMARY KEY NOT NULL,
Date datetime NOT NULL,
Type VARCHAR(20) NOT NULL,
CHECK(Type in ('TRANSFER','INCREMENT','DECREMENT')),
QuantityChange INT,
Description VARCHAR(50),
InventoryLocationIdOld VARCHAR(25),
InventoryLocationIdNew VARCHAR(25),
UserId VARCHAR(25),
ProductId VARCHAR(25),
CompanyId VARCHAR(25) NOT NULL,
FOREIGN KEY(CompanyId) REFERENCES Company(Id),
)
GO